/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedGameSlugRouteImport } from './routes/embed.$gameSlug'
import { Route as GameGameSlugRouteImport } from './routes/game.$gameSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedGameSlugRoute = EmbedGameSlugRouteImport.update({
  id: '/embed/$gameSlug',
  path: '/embed/$gameSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameSlugRoute = GameGameSlugRouteImport.update({
  id: '/game/$gameSlug',
  path: '/game/$gameSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/embed/$gameSlug': typeof EmbedGameSlugRoute
  '/game/$gameSlug': typeof GameGameSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embed/$gameSlug': typeof EmbedGameSlugRoute
  '/game/$gameSlug': typeof GameGameSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/embed/$gameSlug': typeof EmbedGameSlugRoute
  '/game/$gameSlug': typeof GameGameSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/embed/$gameSlug' | '/game/$gameSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/embed/$gameSlug' | '/game/$gameSlug'
  id: '__root__' | '/' | '/embed/$gameSlug' | '/game/$gameSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmbedGameSlugRoute: typeof EmbedGameSlugRoute
  GameGameSlugRoute: typeof GameGameSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$gameSlug': {
      id: '/embed/$gameSlug'
      path: '/embed/$gameSlug'
      fullPath: '/embed/$gameSlug'
      preLoaderRoute: typeof EmbedGameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameSlug': {
      id: '/game/$gameSlug'
      path: '/game/$gameSlug'
      fullPath: '/game/$gameSlug'
      preLoaderRoute: typeof GameGameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmbedGameSlugRoute: EmbedGameSlugRoute,
  GameGameSlugRoute: GameGameSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
